export const AAU_LOCATIONS = [
  '1000 Capacity Lecture Theatre',
  '500 Capacity Lecture Theatre',
  'Administrative Block (Senate)',
  'Ambrose Alli Hall (Male Hostel)',
  'Basic Medical Science Complex',
  'Clinical Science (Irrua/ISTH)',
  'Cordelia Agbebaku Auditorium',
  'E-Library (New Site)',
  'Emotan Hall (Female Hostel)',
  'Faculty of Agriculture Building',
  'Faculty of Arts Complex',
  'Faculty of Education Building',
  'Faculty of Engineering Workshop',
  'Faculty of Environmental Studies',
  'Faculty of Law Building',
  'Faculty of Life Sciences',
  'Faculty of Management Sciences',
  'Faculty of Physical Sciences',
  'Faculty of Social Sciences',
  'Igbinedion Hall',
  'Jericho Campus (Ekpoma)',
  'Kudirat Abiola Hall',
  'Love Garden / Relaxation Center',
  'Main Library (Old Site)',
  'Medical Hostel',
  'New Boys Hostel',
  'New Site Main Gate',
  'Old Site Gate',
  'Professor Iyayi Hall',
  'Rev. Martini Hall',
  'Sports Complex / Pavilion',
  'SUG Secretariat',
  'University Health Centre',
  'University Portals / ICT Center'
];

export const AAU_FACULTIES = [
  'Agriculture',
  'Arts',
  'Basic Medical Sciences',
  'Clinical Sciences',
  'Education',
  'Engineering & Technology',
  'Environmental Studies',
  'Law',
  'Life Sciences',
  'Management Sciences',
  'Physical Sciences',
  'Social Sciences'
];